# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in server.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Kharites-tools}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jose Pablo Barrantes"]
  s.date = %q{2010-05-17}
  s.default_executable = %q{kharites}
  s.description = %q{Tools for Karites.}
  s.email = %q{xjpablobrx@gmail.com}
  s.executables = ["kharites"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "Kharites-tools.gemspec",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/kharites",
     "lib/kharites.rb",
     "lib/kharites/base.rb",
     "lib/kharites/mixins/console.rb",
     "lib/kharites/mixins/generate.rb",
     "lib/kharites/mixins/server.rb",
     "lib/kharites/mixins/sync.rb",
     "lib/kharites/templates/article/article.yml",
     "lib/kharites/templates/article/public/404.html",
     "lib/kharites/templates/article/public/500.html",
     "lib/kharites/templates/article/public/images/article.jpg",
     "lib/kharites/templates/article/public/javascripts/article.js",
     "lib/kharites/templates/article/public/stylesheets/article.css",
     "lib/kharites/templates/article/views/index.haml",
     "lib/kharites/templates/article/views/layout.haml",
     "spec/base_spec.rb",
     "spec/sandbox/test_article/test-article.kharites",
     "spec/sandbox/test_article/views/application.sass",
     "spec/sandbox/test_article/views/index.haml",
     "spec/sandbox/test_article/views/layout.haml",
     "spec/setup_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jpablobr/kharites-tools}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{kharites-tools}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Tools for the Karites.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/setup_spec.rb",
     "spec/base_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0.13.0"])
    else
      s.add_dependency(%q<thor>, [">= 0.13.0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0.13.0"])
  end
end

